"""
Nifty 100 universe: Nifty 50 + Nifty Next 50 constituents.
All symbols use the .NS suffix (NSE format for yfinance).
"""

NIFTY_100: list[str] = [
    # --- Nifty 50 ---
    "ADANIENT.NS",
    "ADANIPORTS.NS",
    "APOLLOHOSP.NS",
    "ASIANPAINT.NS",
    "AXISBANK.NS",
    "BAJAJ-AUTO.NS",
    "BAJFINANCE.NS",
    "BAJAJFINSV.NS",
    "BPCL.NS",
    "BHARTIARTL.NS",
    "BRITANNIA.NS",
    "CIPLA.NS",
    "COALINDIA.NS",
    "DIVISLAB.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "GRASIM.NS",
    "HCLTECH.NS",
    "HDFCBANK.NS",
    "HDFCLIFE.NS",
    "HEROMOTOCO.NS",
    "HINDALCO.NS",
    "HINDUNILVR.NS",
    "ICICIBANK.NS",
    "ITC.NS",
    "INDUSINDBK.NS",
    "INFY.NS",
    "JSWSTEEL.NS",
    "KOTAKBANK.NS",
    "LT.NS",
    "M&M.NS",
    "MARUTI.NS",
    "NTPC.NS",
    "NESTLEIND.NS",
    "ONGC.NS",
    "POWERGRID.NS",
    "RELIANCE.NS",
    "SBILIFE.NS",
    "SHRIRAMFIN.NS",
    "SBIN.NS",
    "SUNPHARMA.NS",
    "TCS.NS",
    "TATACONSUM.NS",
    "TATAMOTORS.NS",
    "TATASTEEL.NS",
    "TECHM.NS",
    "TITAN.NS",
    "ULTRACEMCO.NS",
    "WIPRO.NS",
    "ZOMATO.NS",
    # --- Nifty Next 50 ---
    "ADANIENSOL.NS",
    "ADANIPWR.NS",
    "AMBUJACEM.NS",
    "DMART.NS",
    "ABB.NS",
    "BAJAJHFL.NS",
    "BANKBARODA.NS",
    "BHEL.NS",
    "BOSCHLTD.NS",
    "CGPOWER.NS",
    "CANBK.NS",
    "CHOLAFIN.NS",
    "COLPAL.NS",
    "CUMMINSIND.NS",
    "DLF.NS",
    "GAIL.NS",
    "GODREJCP.NS",
    "HAVELLS.NS",
    "ICICIPRULI.NS",
    "INDIANB.NS",
    "INDHOTEL.NS",
    "INDUSTOWER.NS",
    "IRCTC.NS",
    "IRFC.NS",
    "JINDALSTEL.NS",
    "JIOFIN.NS",
    "LICI.NS",
    "LTIM.NS",
    "LUPIN.NS",
    "MOTHERSON.NS",
    "MUTHOOTFIN.NS",
    "NHPC.NS",
    "NAUKRI.NS",
    "PFC.NS",
    "PIDILITIND.NS",
    "PNB.NS",
    "RECLTD.NS",
    "SAIL.NS",
    "SRF.NS",
    "SHREECEM.NS",
    "SIEMENS.NS",
    "TATAELXSI.NS",
    "TATAPOWER.NS",
    "TORNTPHARM.NS",
    "TRENT.NS",
    "VEDL.NS",
    "VBL.NS",
    "ZYDUSLIFE.NS",
    "UNIONBANK.NS",
    "UBL.NS",
]

COMPANY_NAMES: dict[str, str] = {
    # --- Nifty 50 ---
    "ADANIENT.NS":    "Adani Enterprises",
    "ADANIPORTS.NS":  "Adani Ports and SEZ",
    "APOLLOHOSP.NS":  "Apollo Hospitals Enterprise",
    "ASIANPAINT.NS":  "Asian Paints",
    "AXISBANK.NS":    "Axis Bank",
    "BAJAJ-AUTO.NS":  "Bajaj Auto",
    "BAJFINANCE.NS":  "Bajaj Finance",
    "BAJAJFINSV.NS":  "Bajaj Finserv",
    "BPCL.NS":        "Bharat Petroleum Corporation",
    "BHARTIARTL.NS":  "Bharti Airtel",
    "BRITANNIA.NS":   "Britannia Industries",
    "CIPLA.NS":       "Cipla",
    "COALINDIA.NS":   "Coal India",
    "DIVISLAB.NS":    "Divi's Laboratories",
    "DRREDDY.NS":     "Dr. Reddy's Laboratories",
    "EICHERMOT.NS":   "Eicher Motors",
    "GRASIM.NS":      "Grasim Industries",
    "HCLTECH.NS":     "HCL Technologies",
    "HDFCBANK.NS":    "HDFC Bank",
    "HDFCLIFE.NS":    "HDFC Life Insurance",
    "HEROMOTOCO.NS":  "Hero MotoCorp",
    "HINDALCO.NS":    "Hindalco Industries",
    "HINDUNILVR.NS":  "Hindustan Unilever",
    "ICICIBANK.NS":   "ICICI Bank",
    "ITC.NS":         "ITC",
    "INDUSINDBK.NS":  "IndusInd Bank",
    "INFY.NS":        "Infosys",
    "JSWSTEEL.NS":    "JSW Steel",
    "KOTAKBANK.NS":   "Kotak Mahindra Bank",
    "LT.NS":          "Larsen & Toubro",
    "M&M.NS":         "Mahindra & Mahindra",
    "MARUTI.NS":      "Maruti Suzuki India",
    "NTPC.NS":        "NTPC",
    "NESTLEIND.NS":   "Nestle India",
    "ONGC.NS":        "Oil and Natural Gas Corporation",
    "POWERGRID.NS":   "Power Grid Corporation of India",
    "RELIANCE.NS":    "Reliance Industries",
    "SBILIFE.NS":     "SBI Life Insurance",
    "SHRIRAMFIN.NS":  "Shriram Finance",
    "SBIN.NS":        "State Bank of India",
    "SUNPHARMA.NS":   "Sun Pharmaceutical Industries",
    "TCS.NS":         "Tata Consultancy Services",
    "TATACONSUM.NS":  "Tata Consumer Products",
    "TATAMOTORS.NS":  "Tata Motors",
    "TATASTEEL.NS":   "Tata Steel",
    "TECHM.NS":       "Tech Mahindra",
    "TITAN.NS":       "Titan Company",
    "ULTRACEMCO.NS":  "UltraTech Cement",
    "WIPRO.NS":       "Wipro",
    "ZOMATO.NS":      "Zomato",
    # --- Nifty Next 50 ---
    "ADANIENSOL.NS":  "Adani Energy Solutions",
    "ADANIPWR.NS":    "Adani Power",
    "AMBUJACEM.NS":   "Ambuja Cements",
    "DMART.NS":       "Avenue Supermarts (DMart)",
    "ABB.NS":         "ABB India",
    "BAJAJHFL.NS":    "Bajaj Housing Finance",
    "BANKBARODA.NS":  "Bank of Baroda",
    "BHEL.NS":        "Bharat Heavy Electricals",
    "BOSCHLTD.NS":    "Bosch",
    "CGPOWER.NS":     "CG Power and Industrial Solutions",
    "CANBK.NS":       "Canara Bank",
    "CHOLAFIN.NS":    "Cholamandalam Investment and Finance",
    "COLPAL.NS":      "Colgate-Palmolive (India)",
    "CUMMINSIND.NS":  "Cummins India",
    "DLF.NS":         "DLF",
    "GAIL.NS":        "GAIL (India)",
    "GODREJCP.NS":    "Godrej Consumer Products",
    "HAVELLS.NS":     "Havells India",
    "ICICIPRULI.NS":  "ICICI Prudential Life Insurance",
    "INDIANB.NS":     "Indian Bank",
    "INDHOTEL.NS":    "Indian Hotels Company (Taj Hotels)",
    "INDUSTOWER.NS":  "Indus Towers",
    "IRCTC.NS":       "Indian Railway Catering and Tourism Corporation",
    "IRFC.NS":        "Indian Railway Finance Corporation",
    "JINDALSTEL.NS":  "Jindal Steel & Power",
    "JIOFIN.NS":      "Jio Financial Services",
    "LICI.NS":        "Life Insurance Corporation of India",
    "LTIM.NS":        "LTIMindtree",
    "LUPIN.NS":       "Lupin",
    "MOTHERSON.NS":   "Samvardhana Motherson International",
    "MUTHOOTFIN.NS":  "Muthoot Finance",
    "NHPC.NS":        "NHPC",
    "NAUKRI.NS":      "Info Edge (India) — Naukri",
    "PFC.NS":         "Power Finance Corporation",
    "PIDILITIND.NS":  "Pidilite Industries",
    "PNB.NS":         "Punjab National Bank",
    "RECLTD.NS":      "REC",
    "SAIL.NS":        "Steel Authority of India",
    "SRF.NS":         "SRF",
    "SHREECEM.NS":    "Shree Cement",
    "SIEMENS.NS":     "Siemens India",
    "TATAELXSI.NS":   "Tata Elxsi",
    "TATAPOWER.NS":   "Tata Power Company",
    "TORNTPHARM.NS":  "Torrent Pharmaceuticals",
    "TRENT.NS":       "Trent",
    "VEDL.NS":        "Vedanta",
    "VBL.NS":         "Varun Beverages",
    "ZYDUSLIFE.NS":   "Zydus Lifesciences",
    "UNIONBANK.NS":   "Union Bank of India",
    "UBL.NS":         "United Breweries",
}
